-- 1. Master State Tables
CREATE TABLE "taux_inbox_email_state" (
    "inbox_email_state_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inbox_email_state_description" VARCHAR(255),
    PRIMARY KEY("inbox_email_state_id")
);

CREATE TABLE "taux_outbox_email_state" (
    "outbox_email_state_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "outbox_email_state_description" VARCHAR(255),
    PRIMARY KEY("outbox_email_state_id")
);

-- 2. Users table
CREATE TABLE "tusers" (
    "user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_email" VARCHAR(255),
    "user_name" VARCHAR(255),
    "user_surname" VARCHAR(255),
    PRIMARY KEY("user_id")
);

-- 3. Inbox mail
CREATE TABLE "tinbox" (
    "inbox_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inbox_user_id" INTEGER,
    "inbox_email_remitter" VARCHAR(255),
    "inbox_email_cc" TEXT,
    "inbox_email_subject" VARCHAR(255),
    "inbox_email_body" TEXT,
    "inbox_email_state_id" INTEGER,
    "inbox_email_reception_date" TIMESTAMP,
    PRIMARY KEY("inbox_id"),
    CONSTRAINT "fk_inbox_user" FOREIGN KEY ("inbox_user_id") REFERENCES "tusers"("user_id"),
    CONSTRAINT "fk_inbox_state" FOREIGN KEY ("inbox_email_state_id") REFERENCES "taux_inbox_email_state"("inbox_email_state_id")
);

-- 4. Outbox mail
CREATE TABLE "toutbox" (
    "outbox_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "outbox_user_id" INTEGER,
    "outbox_email_recipient" VARCHAR(255),
    "outbox_email_subject" VARCHAR(255),
    "outbox_email_cc" TEXT,
    "outbox_email_body" TEXT,
    "outbox_email_state_id" INTEGER,
    "outbox_email_update_date" TIMESTAMP,
    PRIMARY KEY("outbox_id"),
    CONSTRAINT "fk_outbox_user" FOREIGN KEY ("outbox_user_id") REFERENCES "tusers"("user_id"),
    CONSTRAINT "fk_outbox_state" FOREIGN KEY ("outbox_email_state_id") REFERENCES "taux_outbox_email_state"("outbox_email_state_id")
);

-- 5. Email states
INSERT INTO "taux_outbox_email_state" ("outbox_email_state_description") VALUES ('Enviado'), ('Borrador'), ('Eliminado');
INSERT INTO "taux_inbox_email_state" ("inbox_email_state_description") VALUES ('Enviado'), ('Eliminado'), ('Spam');